name: Probe QPF

on:
  workflow_dispatch:

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests

      - name: Run probe
        env:
          CWA_KEY: ${{ CWA-3AAC60CC-17EA-4317-AB8E-55351D05680E }}
        run: python probe_qpf.py
